# Generated by Django 5.1.5 on 2026-08-10 15:55

import django.db.models.deletion
import django.db.models.functions.datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('company_name', models.TextField()),
                ('contact_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tax_id', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('category', models.TextField(blank=True, choices=[('Lumber', 'Lumber'), ('Board', 'Board'), ('Beam', 'Beam'), ('Post', 'Post'), ('Sheet', 'Sheet'), ('Veneer', 'Veneer'), ('Firewood', 'Firewood')], db_index=True, null=True)),
                ('length_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thickness_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grade', models.TextField(blank=True, choices=[('FAS', 'Fas'), ('Cabinet grade', 'Cabinet'), ('Select', 'Select'), ('Standard', 'Standard'), ('Construction', 'Construction')], db_index=True, null=True)),
                ('finish', models.TextField(blank=True, choices=[('rough-sawn', 'Rough Sawn'), ('planed', 'Planed'), ('poutre', 'Poutre'), ('kiln-dried', 'Kiln Dried'), ('sanded', 'Sanded')], null=True)),
                ('moisture_content', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True)),
                ('volume_cubic_m', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('uom', models.TextField(choices=[('cbm', 'Cbm'), ('piece', 'Piece'), ('m2', 'M2'), ('linear_m', 'Linear M'), ('ton', 'Ton')], default='cbm')),
                ('cost_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('currency', models.TextField(default='EUR')),
                ('min_stock_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.TextField(unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('ordered', 'Ordered'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft')),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('currency', models.TextField(default='EUR')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'purchase_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('company_name', models.TextField()),
                ('contact_name', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('tax_id', models.TextField(blank=True, null=True)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'suppliers',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('scientific_name', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, choices=[('Hardwood', 'Hardwood'), ('Softwood', 'Softwood'), ('Exotic', 'Exotic')], db_index=True, null=True)),
                ('density_kg_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'wood_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity_received', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_items',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_number', models.TextField(unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.TextField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('partially_shipped', 'Partially Shipped'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='draft')),
                ('subtotal', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('currency', models.TextField(default='EUR')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.client')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.warehouse')),
            ],
            options={
                'db_table': 'sales_orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity_shipped', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.salesorder')),
            ],
            options={
                'db_table': 'sales_order_items',
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.supplier'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_no', models.TextField(unique=True)),
                ('movement_type', models.TextField(choices=[('purchase_in', 'Purchase In'), ('purchase_return', 'Purchase Return'), ('sale_out', 'Sale Out'), ('sale_return', 'Sale Return'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('opening', 'Opening')], db_index=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('lot_number', models.TextField(blank=True, db_index=True, null=True)),
                ('reference_type', models.TextField(blank=True, null=True)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('moved_at', models.DateTimeField(db_index=True, default=django.db.models.functions.datetime.Now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-moved_at'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='wood_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.woodtype'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('reserved_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
            options={
                'db_table': 'inventory',
                'constraints': [models.UniqueConstraint(fields=('product', 'warehouse'), name='inventory_product_warehouse_key'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_quantity_check'), models.CheckConstraint(condition=models.Q(('reserved_qty__gte', 0)), name='inventory_reserved_check')],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['wood_type', 'is_active'], name='products_wood_ty_370831_idx'),
        ),
    ]
