# Generated by Django 5.1.5 on 2026-08-17 12:47

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, choices=[('Bois rouge', 'Redwood'), ('Bois blanc', 'Whitewood'), ('Bois exotique', 'Exotic'), ('Bois noble', 'Noble'), ('Panneaux', 'Panel'), ('Coffrage', 'Formwork')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.TextField(default='MAD'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='currency',
            field=models.TextField(default='MAD'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='currency',
            field=models.TextField(default='MAD'),
        ),
        migrations.CreateModel(
            name='MonthlyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True)),
                ('month', models.IntegerField(db_index=True)),
                ('closing_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('closing_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('purchase_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('sale_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('sale_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('transfer_in_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('transfer_out_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('adjustment_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('opening_qty', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.warehouse')),
            ],
            options={
                'db_table': 'monthly_archive',
                'ordering': ['-year', '-month', 'product__sku'],
                'constraints': [models.UniqueConstraint(fields=('year', 'month', 'product', 'warehouse'), name='archive_product_warehouse_month_key')],
            },
        ),
    ]
