# Generated by Django 5.1.5 on 2026-08-17 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_monthlyarchive'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_threshold_m3',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=4, help_text="Seuil d'alerte de réapprovisionnement en m³. Stock en dessous → alerte.", max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('price_update', 'Price Update'), ('login', 'Login'), ('logout', 'Logout'), ('download', 'Download'), ('reorder', 'Reorder'), ('transfer', 'Transfer'), ('close_month', 'Close Month')], db_index=True)),
                ('entity_type', models.TextField(db_index=True)),
                ('entity_id', models.BigIntegerField(blank=True, null=True)),
                ('entity_ref', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
