# Generated by Django 5.1.5 on 2026-08-18 11:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_product_reorder_threshold_m3_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text="Client bloqué : les ventes sont refusées tant qu'il est bloqué."),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_terms_days',
            field=models.IntegerField(blank=True, help_text='Délai de paiement en jours (calcul des impayés / retards).', null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='customs_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='freight_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='handling_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='allocated_fees',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Part des frais hors sous-total allouée à cette ligne (au m³).', max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='tier_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DryingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.TextField(unique=True)),
                ('status', models.TextField(choices=[('green', 'Green'), ('air_dried', 'Air Dried'), ('kd', 'Kd')], db_index=True, default='green')),
                ('quantity', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('start_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('target_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_moisture', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.warehouse')),
            ],
            options={
                'db_table': 'drying_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('min_volume_m3', models.DecimalField(db_index=True, decimal_places=4, max_digits=14)),
                ('max_volume_m3', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'price_tiers',
                'ordering': ['min_volume_m3'],
                'constraints': [models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 90)), name='price_tiers_discount_range')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField(db_index=True)),
                ('method', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.client')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='stock.salesorder')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-payment_date', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive')],
            },
        ),
    ]
