# Generated by Django 5.1.5 on 2026-08-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_kiln_and_drying_lifecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryingbatch',
            name='status',
            field=models.TextField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='in_progress'),
        ),
    ]
