# Generated by Django 5.1.5 on 2026-08-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_dryingbatch_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='KOUDI STOCK')),
                ('tagline', models.TextField(default='Vente & Gestion de Stock du Bois')),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=120)),
                ('ice', models.CharField(blank=True, default='', max_length=60, verbose_name='ICE')),
                ('registre_commerce', models.CharField(blank=True, default='', max_length=80, verbose_name='Registre de commerce')),
                ('identifiant_fiscal', models.CharField(blank=True, default='', max_length=60, verbose_name='Identifiant fiscal')),
                ('patente', models.CharField(blank=True, default='', max_length=60, verbose_name='Patente')),
                ('cnss', models.CharField(blank=True, default='', max_length=60, verbose_name='CNSS')),
                ('bank_name', models.CharField(blank=True, default='', max_length=120, verbose_name='Banque')),
                ('bank_rib', models.CharField(blank=True, default='', max_length=60, verbose_name='RIB / IBAN')),
            ],
            options={
                'db_table': 'company_profile',
            },
        ),
    ]
