# Generated by Django 5.1.5 on 2026-08-29 13:43

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_companyprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_number', models.TextField(unique=True)),
                ('driver_name', models.TextField(blank=True, null=True)),
                ('truck_plate', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('preparation', 'Preparation'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], db_index=True, default='preparation')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.client')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.warehouse')),
            ],
            options={
                'db_table': 'delivery_notes',
                'ordering': ['-order_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.deliverynote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stock.product')),
            ],
            options={
                'db_table': 'delivery_note_items',
            },
        ),
    ]
