# Generated by Django 5.1.5 on 2026-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_deliverynote_deliverynoteitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.TextField(choices=[('devis', 'Devis'), ('contact', 'Contact')], db_index=True, default='devis')),
                ('name', models.TextField()),
                ('company', models.TextField(blank=True, null=True)),
                ('email', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('requested_lines', models.JSONField(blank=True, default=list)),
                ('status', models.TextField(db_index=True, default='new')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
