# Generated by Django 5.1.5 on 2026-08-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_moroccan_timber_transform'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Paragraphe « description produit » affiché sur la fiche publique.', null=True),
        ),
        migrations.AddField(
            model_name='woodtype',
            name='comarbois_family',
            field=models.TextField(blank=True, choices=[('Menuiserie & Agencement', 'Menuiserie Agencement'), ('Panneaux', 'Panneaux'), ('Aménagement Int./Ext.', 'Amenagement Int Ext'), ('Produits métallurgiques', 'Metallurgique')], db_index=True, help_text='Famille du catalogue (style Comarbois) : Menuiserie & Agencement, Panneaux, Aménagement Int./Ext., Produits métallurgiques.', null=True),
        ),
        migrations.AddField(
            model_name='woodtype',
            name='common_names',
            field=models.TextField(blank=True, help_text="Noms usuels / synonymes (ex: Pin rouge / Sylvestre, Teck d'Afrique pour l'Iroko).", null=True),
        ),
        migrations.AddField(
            model_name='woodtype',
            name='durability_class',
            field=models.TextField(blank=True, help_text='Classe de durabilité naturelle du duramen (NF EN 350) : 1 à 5 (1 = très durable).', null=True),
        ),
        migrations.AddField(
            model_name='woodtype',
            name='moisture_note',
            field=models.TextField(blank=True, help_text="Comportement à l'humidité / séchage (ex: séchage lent, retrait moyen).", null=True),
        ),
        migrations.AddField(
            model_name='woodtype',
            name='provenances',
            field=models.TextField(blank=True, help_text="Provenances / pays d'origine (ex: Scandinavie, Russie, Afrique Centrale, France).", null=True),
        ),
    ]
