# Generated by Django 5.1.5 on 2026-09-03 15:44

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_essence_fiche_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, choices=[('Bois de Construction', 'Construction'), ('Bois Traité Autoclave', 'Autoclave'), ('Bois Feuillus & Nobles', 'Feuillus Nobles'), ('Panneaux & Dérivés', 'Panneaux')], db_index=True, help_text='Catégorie produit éligible (facultatif — grille générique si vide).', null=True)),
                ('piece_type', models.TextField(blank=True, db_index=True, help_text='Type de pièce éligible (Madrier, Basting, Chevron…). Vide = toutes pièces.', null=True)),
                ('treatment', models.TextField(blank=True, db_index=True, help_text='Classe de traitement éligible (Autoclave, Séché KD…). Vide = tous traitements.', null=True)),
                ('target', models.TextField(choices=[('timber', 'Timber'), ('panel', 'Panel')], db_index=True, default='timber')),
                ('unit_price_mad', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Prix de référence de la grille (MAD).', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wood_type', models.ForeignKey(blank=True, help_text='Essence liée (facultatif : laisser vide pour une matière non-attachée à une essence).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_prices', to='stock.woodtype')),
            ],
            options={
                'db_table': 'reference_prices',
                'ordering': ['wood_type__name', 'category', 'piece_type'],
                'indexes': [models.Index(fields=['wood_type', 'category', 'piece_type', 'treatment'], name='reference_p_wood_ty_3f65e1_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('unit_price_mad__gte', 0)), name='reference_prices_price_nonneg')],
            },
        ),
    ]
