# Generated by Django 5.1.5 on 2026-09-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_referenceprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='status',
            field=models.TextField(choices=[('preparation', 'Preparation'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('waiting', 'Waiting'), ('validated', 'Validated'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], db_index=True, default='preparation'),
        ),
    ]
