# Generated by Django 5.1.5 on 2026-09-06 14:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_clientnotification_quote_quoteitem_clientuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Destination de livraison souhaitée (chantier, dépôt client…).', null=True),
        ),
        migrations.CreateModel(
            name='ClientPriceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField(help_text='Libellé affiché au client (ex. « Atelier Premium : −10 % sur le Pin »).')),
                ('scope', models.TextField(choices=[('all', 'All'), ('category', 'Category'), ('wood_type', 'Wood Type')], db_index=True, default='all')),
                ('category', models.TextField(blank=True, choices=[('Bois de Construction', 'Construction'), ('Bois Traité Autoclave', 'Autoclave'), ('Bois Feuillus & Nobles', 'Feuillus Nobles'), ('Panneaux & Dérivés', 'Panneaux')], null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Remise en % appliquée sur le prix de vente catalogue (HT par m³).', max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_discounts', to='stock.client')),
                ('wood_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.woodtype')),
            ],
            options={
                'db_table': 'client_price_discounts',
                'ordering': ['-discount_percent'],
            },
        ),
        migrations.CreateModel(
            name='CreditLimitRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_limit', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.TextField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending')),
                ('decision_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_requests', to='stock.client')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'credit_limit_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(choices=[('volume', 'Volume'), ('adjustment', 'Adjustment')], db_index=True, default='volume')),
                ('points', models.IntegerField(default=0)),
                ('volume_m3', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_ledger', to='stock.client')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_entries', to='stock.salesorder')),
            ],
            options={
                'db_table': 'loyalty_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
