# Generated by Django 5.1.5 on 2026-09-06 17:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0016_b2b_pro_extensions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Facture de regroupement (Facturation groupée) à laquelle ce BL est rattaché.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='stock.salesorder'),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='method_key',
            field=models.TextField(choices=[('cheque', 'Chèque'), ('traite_30', 'Traite bancaire 30 jours'), ('traite_60', 'Traite bancaire 60 jours'), ('traite_90', 'Traite bancaire 90 jours'), ('virement', 'Virement bancaire'), ('especes', 'Espèces'), ('autre', 'Autre moyen')], db_index=True, default='autre'),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.TextField(unique=True)),
                ('reason', models.TextField(choices=[('return', 'Retour de marchandise'), ('volume_correction', 'Correction de volume (m³)'), ('commercial', 'Avoir commercial')], db_index=True, default='return')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=4, help_text='Volume corrigé / retourné (m³) le cas échéant.', max_digits=14, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('applied_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="Part de l'avoir déduite du solde de la facture d'origine.", max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='stock.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('delivery_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='stock.deliverynote')),
                ('sales_order', models.ForeignKey(blank=True, help_text="Facture d'origine à laquelle l'avoir se rattache.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='stock.salesorder')),
            ],
            options={
                'db_table': 'credit_notes',
                'ordering': ['-created_date', '-id'],
            },
        ),
    ]
